language: c
compiler: gcc
matrix:
  include:
    - script: scripts/test-codingstyle.sh
    - script: scripts/test-codingstyle-py.sh
      cache: pip
      install:
        - pip install --user pylint
        - pip install --user pycodestyle
        - pip install --user jsonschema
    - script: scripts/test-build.sh
      cache: ccache
      addons:
        apt:
          packages:
            - libboost-all-dev
            - libjson-c-dev
            - uuid-dev
            - doxygen
    - script: scripts/test-gtapi-mock-drv.sh
      cache: ccache
      addons:
        apt:
          packages:
            - libboost-all-dev
            - libjson-c-dev
            - uuid-dev
            - doxygen
    - env:
        global:
          - secure: "W-f8Jcug5HJU5FSmMs59Dg"
      before_install:
          - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        - coverity_scan:
            project:
                name: "opae-sdk"
                description: "open programmable acceleration engine SDK"
            notification_email: "rodrigo.rojo@intel.com"
            build_command_prepend: "mkdir coverity_scan && pushd coverity_scan && cmake ../"
            build_command: "make"
            branch_pattern: "rrojo/travis-scan"
        - apt:
          packages:
            - libboost-all-dev
            - libjson-c-dev
            - uuid-dev
            - doxygen
