language: c
compiler: gcc
env:
  global:
  - secure: ImJpIxDq0QDS1zCLXPQkZRdwQ1u//zceFlvhJvQaic6jDJI614g09AbsW8nqB2jMKkHf5eGbGUDbgbGXekPZOMEkmYCSnHOGja4wwPuc4x0q/mWJGMKc5bSeCajju6FO0BCWCnXNzg7aOw4lpZhB8LUqQMjFf6/ZbFWFd5FSVZkQ1UhTb65Q0ZboJVf6MV4ApToSdCWCWAFZASgil6Tqe9UYk32+UFnQ47ehNMhXNP7yGzMNGCt3lngQ/XdmK9kZFMxoDnFfwNU9IifqrFrbuUu+DYA/BPY0VSLRJZrtA8uneIkUCxL+vE/bBMwOKXnhgVUo/cPdqwWCBtEzLBIi6qSTczDTebJdEVljBFqUIkfME07KP9Yw6hMxayqnZWFhPsT9x2U85yv2Q4nr2vZ9LG08XqSLt/DRhkSeAOkzrUHbplBEoEQJOV+6v/cvbfWs56JAnuLX2YM63sHLz60gZL/wTU0je61iN+RITIxFWBHzlYY0Ti2G6ZWLqHYvKFjfjCrdEn4xEeNQ0LuwiXLL/DRCPPzkIRbAUBodBBRcHp2VYwPBvktUCrunTVAD/ys0ppO1pdsrAiEuYiAmE0jPAb8z/Fyz+vlYgga6YaUjzj5WdNSSVH6MEU0cWenPr1cUVX0SwCRmuQXRpuMlCqfEMxdt2Bnrz/Qohzh3E88bXHA=
  - secure: AI52eeB9ss+IRJt0d5G4Q1iy9Sphsx9858FySB4bTGMtKakaNRc7fWGTeHvgkfVdWzMV9uEcODF/KJeClX0Y4k2Gi67uG4K7df0DE0MKoMOM/GQOo7THXKrEbN6Ks0Dcs4kd1jzApKRHEVMcI2t3g7IqIgryLFl+0HVh1b5bT1pRayY3o5KPpZSrF9soqRWHICW0oKfyL848WxwFbfBGJWuksYbwRcn6oaHliukGgabNQjvRVRU+8Ukve81xRPU75cNDJIxQhvCO2ciApjv/HkRLsGAPejlJsbgqiD4RRCV11WriYx6id/bdIELgiA7C8WjQlI40nxigT7bxDwVFJLKE+LnnvJlplBmQgo0b9WNVQLHmQqfoUY6OgoBB/54mDd15D6cx9Dcl54dsgZdQUTS1Lu+SLuy+VRyFRBBC29S3f41q1OnJGxhYqdChpnwRSwCPipPQqNEu/FSOICn6xF4cDau7UDgEffVdbUR5A+cuLGHW/Cwd3AJD17TeclcNCCFtzmi7W8KQ0zKOf/JBKHTxyg2SgXn7IVjO0/IAkx8mtL/25Q4QRpRik6LuQ5DOF2PPdQw6EMzBo1bRstBrc5ZT/w7YAXMIPdU95iE4G3Ssbf+8qSVQBhP3hXzJprWsPFFmwC9RzYe9Bb0z5pWCh6ltISoe6n6bQ1CtwPu09c8=
script: echo "coverity_scan"
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- ./scripts/merge-master.sh
addons:
  coverity_scan:
    project:
      name: opae-sdk
      description: open programmable acceleration engine SDK
    notification_email: rodrigo.rojo@intel.com
    build_command_prepend: mkdir coverity_scan && pushd coverity_scan && cmake ../
    build_command: make
    branch_pattern: coverity_scan
  apt:
    packages:
    - libboost-all-dev
    - libjson-c-dev
    - uuid-dev
